---
engines:
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD026:
        enabled: false
  kibit:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.clj"
