---
engines:
  # CSS checks
  csslint:
    enabled: true
  # disallow FIX-ME comments
  fixme:
    enabled: true
  # assure good style in README.md
  markdownlint:
    enabled: true
    checks:
      # disable a check that limits line length - I don't want to insert line breake in code snippets
      MD013:
        enabled: false
      # disable a check that disallows using punctation in headers - "Why?" should be a legtimate header
      MD026:
        enabled: false
  # suggest more idiomatic clojure
  kibit:
    enabled: true
  # check the few lines of shell scripts as well
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.md"
  - "**.clj"
  - "**.sh"

